- name: Carga de la imagen de un servidor web al ACR de Azure
  hosts: unir-vm
  vars_files:
    - vars.yml    
  become: yes
  tasks: 

    - name: Build a Docker formatted image
      containers.podman.podman_image:
         name: httpd
         path: /path/to/build/dir
         build:
           format: docker    
    
    - name: Arrancar contenedor Docker
      containers.podman.podman_container:
        name: httpd_container
        image: httpd:casopractico2
        state: started
        ports:
          - 8080:80

