#Fichero inventario para realizar conexiones a la VM de Azure
all:
  hosts:
    #Declaramos el host unir-vm que apuntará a la V; d Azure
    unir-vm:
      #Recuperamos los valores de la IP publica, el usuario y la ruta a la clave prmaria
      #a partir de los parametros del fichero de variables
      ansible_host: "{{ azure_vm_ip }}"
      ansible_user: "{{ azure_user }}"
      ansible_ssh_private_key_file: "{{ azure_ssh_path }}"
