tasks: 
    - name: Descargar imagen de Apache HTTP Server para Ubuntu 22.04
      containers.podman.podman_image:
        name: docker.io/nginx

    - name: Añadimos un nombre a la imagen descargada
      containers.podman.podman_tag:
        image: docker.io/nginx:latest
        target_names: 
            - nginx:CP2

    - name: Subimos la imagen a ACR
      containers.podman.podman_image:
        name: nginx:CP2
        push: true            
