- name: Carga de las imagenes necesarias para la instalación de una aplicaccion en Kubernetes
  hosts: unir-vm
  vars_files:
    - vars.yml  
  become: yes
  tasks: 
  
    - name: Descargar imagen Microsoft Redis
      containers.podman.podman_image:
        name: mcr.microsoft.com/oss/bitnami/redis:6.0.8

    - name: Renombramos la imagen descargada a casopractico2
      containers.podman.podman_tag:
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        target_names: 
          - redis:casopractico2

    - name: Subimos la imagen Redis a ACR
      containers.podman.podman_image:
        name: redis:casopractico2
        push: true    
        username: "azMraACR"
        password: "8EflDLT7d8loqAz0x14jnp74D4urAJ/WWzOQVk0CMl+ACRAIpiwL"
        push_args:
          dest: azmraacr.azurecr.io     


    - name: Descargar imagen Azure Frontal
      containers.podman.podman_image:
        name: mcr.microsoft.com/azuredocs/azure-vote-front:v1

    - name: Renombramos la imagen descargada a casopractico2
      containers.podman.podman_tag:
        image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
        target_names: 
          - azure_frontal:casopractico2

    - name: Subimos la imagen Azure Frontal a ACR
      containers.podman.podman_image:
        name: azure_frontal:casopractico2
        push: true    
        username: "azMraACR"
        password: "8EflDLT7d8loqAz0x14jnp74D4urAJ/WWzOQVk0CMl+ACRAIpiwL"
        push_args:
          dest: azmraacr.azurecr.io                     
